#!/bin/bash
set -x
img=${1:-guest_disk.img}
port=${2}

[[ -z $port ]] && port=$RANDOM

if [[ $(uname) == Darwin ]]; then
    accel=hvf
else
    accel=kvm
fi

# -append "console=ttyS0 root=/dev/sda mitigations=off nosmep nosmap ip=192.168.19.130:::255.255.255.0::eth0:none isolcpus=0"
# put the above in grub config
echo $port > sym.sshport

qemu-system-x86_64 -M accel=$accel -smp cpus=2 -m 10G -hda $img -nodefaults -nographic -serial stdio \
   -monitor unix:monitor.sock,server,nowait \
   -device virtio-net-pci,mq=on,vectors=10,mac=02:00:00:04:00:29,netdev=p00 \
   -netdev user,id=p00,hostfwd=tcp::$port-:22

#-net nic,model=virtio,macaddr=54:54:00:55:55:55 \
#-net tap,script=./tap-up,downscript=./tap-down

		   
