#!/bin/bash
#set -x
set -e
img=${1:-guest_disk.img}
port=${2}

# to get a better stable console that passes control-c to guest use
SERIAL="mon:stdio"
# otherwise use this to allow control-c to kill instance
#SERIAL="stdio"


# if TAG is not empty then attempt to start the image with snapshot specified
# eg to use : TAG=symbooted ./do guest-disk.qcow2 
if [[ -n $TAG ]]; then
   if  qemu-img snapshot -l $img | grep " $TAG "; then
       TAG="-loadvm $TAG"
   else
       echo "ERROR: $TAG is not a snapshot in $img:" > /dev/stderr
       qemu-img snapshot -l $img > /dev/stderr
       exit -1
   fi
fi


[[ -z $port ]] && port=$RANDOM

if [[ $(uname) == Darwin ]]; then
    accel=hvf
else
    accel=kvm
fi

# -append "console=ttyS0 root=/dev/sda mitigations=off nosmep nosmap ip=192.168.19.130:::255.255.255.0::eth0:none isolcpus=0"
# put the above in grub config
echo $port > sym.sshport

set -x
qemu-system-x86_64 -M accel=$accel -smp cpus=2 -m 10G -hda $img -nodefaults -nographic -serial $SERIAL $TAG\
   -monitor unix:monitor.sock,server,nowait \
   -device virtio-net-pci,mq=on,vectors=10,mac=02:00:00:04:00:29,netdev=p00 \
   -netdev user,id=p00,hostfwd=tcp::$port-:22 

#-net nic,model=virtio,macaddr=54:54:00:55:55:55 \
#-net tap,script=./tap-up,downscript=./tap-down

		   
