virt-install \
	--name fed36 \
	--description 'Fedora 36 Server' \
	--ram 40960 \
	--vcpus 46 \
	--disk path=/dev/sda1 \
	--os-type linux \
	--os-variant fedora31 \
	--network bridge=virbr0,model=virtio \
	--graphics none \
	--boot hd
