virt-install \
	--name fed35 \
	--description 'Fedora 35 Server' \
	--ram 40960 \
	--vcpus 46 \
	--disk path=guest_disk.img \
	--os-type linux \
	--os-variant fedora34 \
	--network bridge=virbr0,model=virtio \
	--graphics none \
	--boot hd
